# Generated by Django 4.2.1 on 2023-06-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stuent",
            new_name="Student",
        ),
    ]
